- name: "✨ enhancement"
  color: 0000ff
  description: New features or request!!!!!!!!!!

- name: "🐛 bug"
  color: d73a4a
  description: Something isn't working

- name: "📚 documentation"
  color: 0075ca
  description: Improvements or additions to documentation

- name: "🎉 good first issue"
  color: 7057ff
  description: Good for newcomers

- name: "🏷️ new tag test!"
  color: f9d0c4
  description: Test label for new tags
