- name: enhancement
  color: a2eeef
  description: New feature or request

- name: bug
  color: d73a4a
  description: Something isn't working

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: question
  color: d876e3
  description: Further information is requested

- name: good first issue
  color: 7057ff
  description: Good for newcomers
