version: "2"

run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly


linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - nlreturn
    - gofumpt
    - gci
    - exportloopref
    - prealloc
    - unconvert
    - unparam
    - gocyclo
    - dupl

issues:
  max-same-issues: 3
  max-issues-per-linter: 0