name: "Epic"
description: "複数の関連するIssueをまとめるもの"
title: "[Epic] "
labels: ["type: epic", "need: triage"]
body:
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "このEpicが完了したときに、どのような状態になっているべきかを簡潔に"
      placeholder: |
        ex. ユーザーが新しいダッシュボード機能を使えるようになっている
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason"
      description: "なぜ、このEpicが必要なのか"
      placeholder: "ex. 既存のダッシュボードでは、ユーザーが必要な情報を一覧できず、UXを損なっているため。"

  - type: textarea
    id: in-scope
    attributes:
      label: "In Scope"
      description: "このEpicで実施する作業を具体的にリストアップしてください。"
      placeholder: |
        - ダッシュボードのUIデザイン実装
        - データ表示のためのAPI開発

  - type: textarea
    id: out-of-scope
    attributes:
      label: "Out of Scope"
      description: "このEpicでは実施しない作業を明記してください。\n関係者間の認識のズレを防ぎます。"
      placeholder: |
        - ユーザー認証機能の改修
        - PDFエクスポート機能
        
  - type: textarea
    id: related-issues
    attributes:
      label: "✅ Related Issues / Tasks (関連Issue / タスク)"
      description: "このEpicを達成するために必要なIssueやタスクをリストアップしてください。"
      placeholder: |
        - #123 (フロントエンドの実装)
        - #124 (バックエンドAPIの開発)
        - [ ] デザインカンプの作成

  - type: textarea
    id: definition-of-done
    attributes:
      label: "🏁 Definition of Done (完了の定義)"
      description: "何をもってこのEpicが「完了」したと判断するか、具体的な基準を記述してください。"
      placeholder: |
        - [ ] 新しいダッシュボード機能が、全てのテストを通過して本番環境にデプロイされている
        - [ ] 関係者（プロダクトマネージャー、デザイナーなど）のレビューが完了している
        - [ ] ユーザーマニュアルが更新されている

  - type: textarea
    id: references
    attributes:
      label: "References"
      description: "関連するドキュメント、Figmaのリンクなどがあれば記述してください。"
      placeholder: |
        - [Figmaデザイン](http://example.com)
        - [要件定義書](http://example.com)