name: "その他 (Chore)"
description: "ビルドプロセス、設定ファイル、ドキュメントの更新など、上記以外のタスク。"
title: "[Chore] "
body:
  - type: markdown
    attributes:
      value: |
        タスクの起票ありがとうございます！
        以下の項目を記入してください。
  - type: textarea
    id: overview
    attributes:
      label: "概要 (Overview)"
      description: "どのようなタスクですか？"
      placeholder: "例：ライブラリのバージョンをアップグレードする"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "優先度 (Priority)"
      description: "この issue の優先度を選択してください。"
      options:
        - "priority: could - 必須ではない"
        - "priority: should - 品質向上のために対応が推奨"
        - "priority: must - これがないとリリースできない"
        - "priority: critical - 最優先で対応すべき"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: "関連領域 (Area)"
      description: "この issue が関連する領域を選択してください。ドキュメント修正の場合は 'area: docs' を選択してください。"
      multiple: true
      options:
        - "area: docs"
        - "area: infra"
        - "area: frontend"
        - "area: backend"
    validations:
        required: true
  - type: checkboxes
    id: tasks
    attributes:
      label: "タスクリスト (Tasks)"
      description: "このタスクを完了するために必要な作業をリストアップしてください。"
      options:
        - label: "例：設定ファイルの更新"
        - label: "例：動作確認"
  - type: textarea
    id: details
    attributes:
      label: "詳細 (Details)"
      description: "タスクの背景や目的、参考情報などがあれば記入してください。"