name: "Enhancement"
description: "新しい機能や既存機能の改善を提案"
title: "feat: "
labels: ["type: enhancement"]

body:
  - type: markdown
    attributes:
    value: |
      ### Introduction

      - 全てのセクションを記入する必要はありません
        - issueの内容や難易度に応じて、必要なセクションのみを記入してください
      - ラベルをつけていただけると助かります
        - 自動化やフィルタリングに役立ちます

  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "どのような機能改善をしたいかの概要を簡潔に記入してください。"
      placeholder: |
        例: ユーザーがCSVでデータをエクスポートできる機能の実装
    validations:
      required: true
        
  - type: textarea
    id: implementation-plan
    attributes:
      label: "Implementation Plan"
      description: "具体的な実装計画や技術的なアプローチを記入してください。"
      placeholder: |
        - APIエンドポイントを作成する
        - ライブラリを使用してCSVを生成する
        - 画面にダウンロードボタンを設置する

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "何ができたらこのIssueを完了と見なすかの基準を明確にしてください。"
      placeholder: |
        - [ ] 画面にCSVダウンロードボタンが表示される
        - [ ] ダウンロードしたCSVにA, B, Cの列が含まれている

  - type: textarea
    id: dev-tasks
    attributes:
      label: "Tasks"
      description: "作業で必要なら、タスクリストを活用してください。"
      placeholder: |
        - [ ] タスク1
        - [ ] タスク2

  - type: textarea
    id: references
    attributes:
      label: "References"
      description: "参考になる情報や関連情報があれば記入してください。"
      placeholder: |
        - #123
        - Figma: [Link]
