name: Comment out `_No response_` sections on issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment-no-response:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Comment out `_No response_` sections
        uses: actions/github-script@v6
        env:
          MIN_HEADING_LEVEL: '3'
          TARGET_HEADING_PATTERN: '^(Implementation Plan|Acceptance Criteria|Tasks|References)$'
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue) {
              core.info('No issue payload found.');
              return;
            }
            const originalBody = issue.body || '';

            const MIN_HEADING_LEVEL = Number(process.env.MIN_HEADING_LEVEL) || 3;
            const TARGET_HEADING_PATTERN_RAW = process.env.TARGET_HEADING_PATTERN || '';
            let TARGET_HEADING_RE = null;
            if (TARGET_HEADING_PATTERN_RAW.trim()) {
              try { TARGET_HEADING_RE = new RegExp(TARGET_HEADING_PATTERN_RAW, 'i'); } catch (e) { core.info(`Invalid TARGET_HEADING_PATTERN ignored: ${TARGET_HEADING_PATTERN_RAW}`); }
            }

            function transform(body) {
              const lines = body.split(/\r?\n/);
              let out = '';
              let i = 0;
              while (i < lines.length) {
                const line = lines[i];
                const heading = line.match(/^(#{1,6})\s(.*)$/);
                if (heading) {
                  const level = heading[1].length;
                  const headingText = heading[2].trim();
                  // collect block until next heading
                  let j = i + 1;
                  const block = [line];
                  while (j < lines.length && !lines[j].match(/^(#{1,6}\s.*)$/)) {
                    block.push(lines[j]);
                    j++;
                  }
                  const contentLines = lines.slice(i + 1, j);
                  const contentTrim = contentLines.join('\n').trim();
                  // only when heading level >= configured minimum
                  // and when TARGET_HEADING_NAME is empty or matches this heading text
                  const targetMatch = !TARGET_HEADING_RE || TARGET_HEADING_RE.test(headingText);
                  if (level >= MIN_HEADING_LEVEL && targetMatch && contentTrim === '_No response_') {
                    // comment out heading+block and add a blank line after
                    out += '<!--\n' + block.join('\n') + '\n-->\n\n';
                  } else {
                    out += block.join('\n') + (j < lines.length ? '\n' : '');
                  }
                  i = j;
                } else {
                  out += line + '\n';
                  i++;
                }
              }
              // remove trailing single newline added above if the original didn't have it
              if (!body.endsWith('\n') && out.endsWith('\n')) out = out.slice(0, -1);
              return out;
            }

            const newBody = transform(originalBody);
            if (newBody !== originalBody) {
              core.info('Updating issue body to comment out `_No response_` sections.');
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: newBody,
              });
            } else {
              core.info('No changes required.');
            }
