name: Backend CI

on:
  workflow_call:
    inputs:
      skip_lint:
        type: boolean
        required: false
        default: false
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: backend

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Lint (golangci-lint)
        if: ${{ !inputs.skip_lint }}
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: backend

      - name: Skip notice
        if: ${{ inputs.skip_lint }}
        run: echo "skip-lint を含むラベルが付与されているため golangci-lint をスキップしました"

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Print Go cache paths (debug)
        run: |
          echo "GOMODCACHE=$(go env GOMODCACHE)"
          echo "GOCACHE=$(go env GOCACHE)"

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Build
        run: go build ./...
