name: Backend CI

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      enable-lint:
        description: 'Lintを有効にするかどうか'
        required: false
        default: 'true'

defaults:
  run:
    working-directory: backend

jobs:
  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Lint (golangci-lint)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.enable-lint == 'true' || github.event_name != 'workflow_dispatch' }}
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: backend

      - name: Build
        run: go build ./...
