name: Frontend CI

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute cache key hash
        id: compute-cache-hash
        run: |
          if [ -f package-lock.json ]; then
            HASH=$(sha256sum package-lock.json | awk '{print $1}')
          else
            HASH=missing
          fi
          echo "cache-hash=$HASH" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Restore node_modules cache
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ steps.compute-cache-hash.outputs.cache-hash }}

      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Format Check
        run: npm run format:check

      - name: Lint Check
        run: npm run lint:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute cache key hash
        id: compute-cache-hash
        run: |
          if [ -f package-lock.json ]; then
            HASH=$(sha256sum package-lock.json | awk '{print $1}')
          else
            HASH=missing
          fi
          echo "cache-hash=$HASH" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Restore node_modules cache
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ steps.compute-cache-hash.outputs.cache-hash }}

      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build
